/**
 * @file    main.cpp
 * @brief   Main method of the PID implementations reliabilities testbench
 *
 * @author  Tiago Pereira Vidigal
 * @version 1.0
 * 
 * This testbench takes files generated by the Golden Model in Matlab to
 * run multiple PID implementations and generate time to fail data
 * 
 */
/*------------------------------------------------------------------------------
 *
 * History
 *
 * Version  Date        Author       Note
 * 1.0      2016/11/12  TVIDIGAL     Document created based on tb_PID_Matlab
 *                                   and tb_Fault_Analysis
 *
 *----------------------------------------------------------------------------*/

#include <systemc.h>
#include "tb_Reliability.hpp"


/* Main **********************************************************************/

///Start simulation
int sc_main(int argc, char* argv[]) {

	tb_Reliability tb("Testbench_Reliability");
	
	sc_start();
	return 0;
}
