/**
 * @file    main.cpp
 * @brief   Main method of the System Matlab testbench
 *
 * @author  Tiago Pereira Vidigal
 * @version 1.0
 * 
 * This testbench takes files generated by the Golden Model in Matlab to
 * validate the SystemC model of a Control System
 * 
 */
/*------------------------------------------------------------------------------
 *
 * History
 *
 * Version  Date        Author       Note
 * 1.0      2016/09/21  TVIDIGAL     Document adapted from PID TB's main.
 *
 *----------------------------------------------------------------------------*/

#include <systemc.h>
#include "tb_System_Matlab.hpp"


/* Main **********************************************************************/

///Start simulation
int sc_main(int argc, char* argv[]) {

	tb_System_Matlab tb("Testbench_Matlab");
	sc_start();
	return 0;
}
