/**
 * @file    main.cpp
 * @brief   Main method of the Plant testbench
 *
 * @author  Tiago Pereira Vidigal
 * @version 1.0
 * 
 * This testbench takes files generated by the Golden Model in Matlab to
 * validate the SystemC model of a Plant
 * 
 */
/*------------------------------------------------------------------------------
 *
 * History
 *
 * Version  Date        Author       Note
 * 1.0      2016/10/17  TVIDIGAL     Document adapted from Control System TB
 *
 *----------------------------------------------------------------------------*/

#include <systemc.h>
#include "tb_Plant.hpp"


/* Main **********************************************************************/

///Start simulation
int sc_main(int argc, char* argv[]) {

	tb_Plant tb("Testbench_Matlab");
	sc_start();
	return 0;
}
